#!/bin/bash

# make sure name-resolver is killed
sudo pkill name-resolver

# start UN

#cleanup
sudo ovs-vsctl del-br Bridge1
sudo ovs-vsctl del-br Bridge2


#start name-resolver
sudo ./start_name_resolver &

#start orchestrator
cp orchestrator_config_er_demo.ini ../../../orchestrator/config/
cp universal-node-er-demo.xml ../../../orchestrator/config/
cp nffg_files/er_nffg.json ../../../orchestrator/config/


cd ../../../orchestrator/
sudo ./node-orchestrator --d ./config/orchestrator_config_er_demo.ini &

#start virtualizer
cd ../virtualizer
gunicorn -b 0.0.0.0:9090 virtualizer:api --timeout 60
#sudo ./start_virtualizer &


#after kill make sure dockers are removed
docker rm -f 2_ctrl 2_ovs1 2_ovs2 2_ovs3 2_ovs4 2_ovs5

# kill last backgrounded process (name-resolver or node orchestrartor)
kill $!
 
